name: Debian

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: ${{ matrix.compiler.name }} + ${{ matrix.arch }} + ${{ matrix.compiler.debian }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        arch:
        - amd64
        # - i386

        compiler:

        # - name: gcc
        #   debian: experimental
        # - name: clang
        #   debian: experimental




        # WORKING
        - name: gcc-13
          debian: trixie
        # - name: gcc-12
        #   debian: bookworm
        # - name: gcc-11
        #   debian: bookworm
        # - name: gcc-10
        #   debian: bullseye
        # - name: gcc-9
        #   debian: bullseye
        # - name: gcc-8
        #   debian: buster
        # - name: gcc-7
        #   debian: buster


        - name: gcc-6
          debian: buster
          repo: bionic

        - name: gcc-5
          debian: buster
          repo: bionic

        - name: gcc-4
          debian: buster
          repo: bionic


        # - name: clang-17
        #   debian: trixie

        # - name: clang-16
        #   debian: bookworm

        # - name: clang-15
        #   debian: bookworm

        # - name: clang-14
        #   debian: bookworm

        # - name: clang-13
        #   debian: bookworm

        - name: clang-12
          debian: bullseye
          repo: stretch

        # - name: clang-11
        #   debian: bullseye

        - name: clang-10
          debian: bullseye
          repo: stretch

        # - name: clang-9
        #   debian: bullseye

        - name: clang-8
          debian: bookworm
          repo: stretch

        # - name: clang-7
        #   debian: buster

        - name: clang-6
          debian: bullseye
          repo: stretch



    container:
      image: ${{ matrix.arch }}/debian:${{ matrix.compiler.debian }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v1
    #   with:
        # show-progress: 'false'

    - name: Install packages
      if: matrix.compiler.repo
      run: |
        echo "deb http://azure.archive.ubuntu.com/ubuntu ${{ matrix.compiler.repo }} main" >> /etc/apt/sources.list
        echo "deb http://azure.archive.ubuntu.com/ubuntu ${{ matrix.compiler.repo }} universe" >> /etc/apt/sources.list


    - name: whoami
      run: id

    - name: Install packages
      run: |
            apt-get update -qq
            apt-get install -yq make ${{ matrix.compiler.name }}

    - name: Display ${{ matrix.compiler.name }} version
      run: ${{ matrix.compiler.name }} -v

    - name: Display uname
      run: |
        uname -a
        uname -m

    - name: configure (unix/Makefile)
      run: |
        make -j2 -f unix/Makefile generic CC=${{ matrix.compiler.name }} LOCAL_ZIP="-Werror" ${{ matrix.opts }}
        cat flags

    - name: Run zip -v
      run: ./zip -v


    # - name: build (unix/Makefile)
    #   run: |
    #         make -j2 -f unix/Makefile generic

    # - name: Run zip -v
    #   run: ./zip -v

    # - name: Run zipcloak -v
    #   run: ./zipcloak -v

    # - name: Run zipnote -v
    #   run: ./zipnote -v

    # - name: Run zipsplit -v
    #   run: ./zipsplit -v

