name: Debian

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: ${{ matrix.compiler.name }}+ ${{ matrix.arch }} + ${{ matrix.compiler.debian }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        arch:
        - amd64
        - i386

        compiler:

        - debian: experimental
          name: gcc
        - debian: experimental
          name: clang



        # - debian: trixie
        #   name: gcc-13
        # - debian: bookworm-slim
        #   name: gcc-12
        # - debian: bookworm-slim
        #   name: gcc-11
        # - debian: bullseye-slim
        #   name: gcc-10
        # - debian: bullseye-slim
        #   name: gcc-9
        # - debian: buster-slim
        #   name: gcc-8
        # - debian: buster-slim
        #   name: gcc-7
        - debian: buster-slim
          name: gcc-6
        - debian: buster-slim
          name: gcc-5
        - debian: buster-slim
          name: gcc-4

        # - debian: trixie
        #   name: clang-17
        # - debian: bookworm-slim
        #   name: clang-16
        # - debian: bookworm-slim
        #   name: clang-15
        # - debian: bookworm-slim
        #   name: clang-14
        # - debian: bookworm-slim
        #   name: clang-13
        # # - debian: bullseye-slim
        # #   name: clang-12
        # - debian: bullseye-slim
        #   name: clang-11
        # # - debian: bullseye-slim
        # #   name: clang-10
        # - debian: bullseye-slim
        #   name: clang-9
        # # - debian: bookworm-slim
        # #   name: clang-8
        # - debian: buster-slim
        #   name: clang-7
        # # - debian: bullseye-slim
        # #   name: clang-6



    container:
      image: ${{ matrix.arch }}/debian:${{ matrix.compiler.debian }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v1
    #   with:
        # show-progress: 'false'

    - name: Install packages
      run: |
        apt-get update -qq
        apt-get install -yq make ${{ matrix.compiler.name }}

    - name: Display ${{ matrix.compiler.name }} version
      run: ${{ matrix.compiler.name }} -v

    - name: Display uname
      run: uname -a

    - name: configure (unix/Makefile)
      run: |
        make -f unix/Makefile generic CC=${{ matrix.compiler.name }} LOCAL_ZIP="-Werror" ${{ matrix.opts }}
        cat flags

    - name: Run zip -v
      run: ./zip -v


    # - name: build (unix/Makefile)
    #   run: |
    #         make -f unix/Makefile generic

    # - name: Run zip -v
    #   run: ./zip -v

    # - name: Run zipcloak -v
    #   run: ./zipcloak -v

    # - name: Run zipnote -v
    #   run: ./zipnote -v

    # - name: Run zipsplit -v
    #   run: ./zipsplit -v

