name: Linux 32-bit

on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: ${{ matrix.compiler.name }} + ${{ matrix.arch }}  ${{ matrix.opts }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        arch:
        - name: amd64
          cc: -m64
        - name: i386
          cc: -m32

        opts:
          - ""
          - "IZ_ZLIB=/tmp IZ_BZIP2=/tmp"
          - "NO_AES_WG=1 NO_IZ_BZIP2=1 NO_LZMA=1 NO_PPMD=1 NO_NAT_ICONV=1 NO_ICONV=1 NO_UNICODE_SUPPORT=1"

        compiler:

          # https://wiki.debian.org/DebianReleases
          # See https://hub.docker.com/_/debian/tags

        # # Bleeding Edge
        # - name: gcc
        #   tag: debian:testing-slim
        # - name: clang
        #   tag: debian:testing-slim

        # # GCC
        - name: gcc-13
          tag: debian:trixie-slim
        # - name: gcc-12
        #   tag: debian:bookworm-slim
        # - name: gcc-11
        #   tag: debian:bookworm-slim
        # - name: gcc-10
        #   tag: debian:bullseye-slim
        # - name: gcc-9
        #   tag: debian:bullseye-slim
        # - name: gcc-8
        #   tag: debian:buster-slim
        # - name: gcc-7
        #   tag: debian:buster-slim


        # # CLANG
        - name: clang-17
          tag: debian:trixie-slim
        # - name: clang-16
        #   tag: debian:bookworm-slim
        # - name: clang-15
        #   tag: debian:bookworm-slim
        # - name: clang-14
        #   tag: debian:bookworm-slim
        # - name: clang-13
        #   tag: debian:bookworm-slim
        # - name: clang-11
        #   tag: debian:bullseye-slim
        # - name: clang-9
        #   tag: debian:bullseye-slim
        # - name: clang-7
        #   tag: debian:buster-slim


        # TODO
        # Need to figure out how to read 386 image from
        # https://hub.docker.com/r/debian/eol/tags


        # - name: gcc-6
        #   tag: debian/eol:stretch-slim
        # - name: gcc-5
        #   tag: debian/eol:stretch
        # - name: gcc-4
        #   tag: debian/eol:stretch

        # - name: clang-12
        #   tag: debian/eol:stretch
        # - name: clang-10
        #   tag: debian/eol:stretch
        # - name: clang-8
        #   tag: debian/eol:stretch
        # - name: clang-6
        #   tag: debian/eol:stretch



    container:
      image: ${{ matrix.arch.name }}/${{ matrix.compiler.tag }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v1
    #   with:
        # show-progress: 'false'

    - name: whoami
      run: id

    - name: Install packages
      run: |
            apt-get update -qq
            apt-get install -yq make ${{ matrix.compiler.name }}

    - name: Display ${{ matrix.compiler.name }} version
      run: ${{ matrix.compiler.name }} -v

    - name: Display uname
      run: |
        uname -a
        uname -m

    - name: configure (unix/Makefile)
      run: |
        make -j2 -f unix/Makefile generic CC=${{ matrix.compiler.name }} LOCAL_ZIP="-Werror ${{ matrix.arch.cc }}" ${{ matrix.opts }}
        cat flags

    - name: Run zip -v
      run: ./zip -v

    - name: Run zipcloak -v
      run: ./zipcloak -v

    - name: Run zipnote -v
      run: ./zipnote -v

    - name: Run zipsplit -v
      run: ./zipsplit -v


