name: Debian

# Note - adding NO_ASM to the build for now. 32-bit build cores otherwise.
# See https://github.com/info-zip/zip-demo/issues/19

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: ${{ matrix.debian }} + ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:

        # debian:
        #   - experimental
        #   - bookworm-slim # 12
        # #   - bullseye-slim # 11
        # #   - buster-slim   # 10

        include:
        - debian: experimental
          compiler: gcc
        - debian: experimental
          compiler: clang
        - debian: bookworm-slim
          compiler: gcc-12
        - debian: bookworm-slim
          compiler: gcc-11
        - debian: bullseye-slim
          compiler: gcc-10
        - debian: bullseye-slim
          compiler: gcc-9
        - debian: buster-slim
          compiler: gcc-8
        - debian: buster-slim
          compiler: gcc-7
        - debian: buster-slim
          compiler: gcc-6
          
        - debian: bookworm-slim
          compiler: clang-14
        - debian: bookworm-slim
          compiler: clang-13

                # - gcc
                # - clang
            # - debian: debian:bookworm-slim
            #   compiler:
            #     - gcc-12
            #     - clang-14

        compiler:
        - gcc
        - clang

    container:
      image: debian:${{ matrix.debian }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        show-progress: 'false'

    - name: Install packages
      run: |
        apt-get update -qq
        apt-get install -yq ${{ matrix.compiler }}

    - name: Display ${{ matrix.compiler }} version
      run: ${{ matrix.compiler }} -v

    # - name: configure (unix/Makefile)
    #   run: |
    #     make -f unix/Makefile flags CC=${{ matrix.compiler }} LOCAL_ZIP="-Werror -DNO_ASM" ${{ matrix.opts }}
    #     cat flags

    # - name: build (unix/Makefile)
    #   run: |
    #         make -f unix/Makefile generic

    # - name: Run zip -v
    #   run: ./zip -v

    # - name: Run zipcloak -v
    #   run: ./zipcloak -v

    # - name: Run zipnote -v
    #   run: ./zipnote -v

    # - name: Run zipsplit -v
    #   run: ./zipsplit -v

