name: FreeBSD

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: FreeBSD + ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - gcc
        - clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
          # temp hard-code to build branch
          ref: build

      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            ASSUME_ALWAYS_YES=YES pkg install ${{ matrix.compiler }}
            ${{ matrix.compiler }} -v
            make -f unix/Makefile flags CC=${{ matrix.compiler }} ZIP_LOCAL="-Werror"
            cat flags
            make -f unix/Makefile generic
            ./zip -help
            ./zip -v
            ./zipnote -help
            ./zipnote -v
            ./zipsplit -help
            ./zipsplit -v
