name: FreeBSD

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: FreeBSD
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
          # temp hard-code to build branch
          ref: build

      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            cc -v

            make -f unix/Makefile flags ZIP_LOCAL="-Werror" PROD=default
            cat default/flags
            make -f unix/Makefile generic PROD=default

            ./default/zip -v
            ./default/zipnote -v
            ./default/zipsplit -v

            make -f unix/Makefile flags ZIP_LOCAL="-Werror" PROD=disable NO_AES_WG=1 NO_IZ_BZIP2=1 NO_LZMA=1 NO_PPMD=1 NO_NAT_ICONV=1 NO_ICONV=1 NO_UNICODE_SUPPORT=1
            ./disable/zip -help
            cat disable/flags
            make -f unix/Makefile generic PROD=disable

            ./disable/zip -v
            ./disable/zipnote -v
            ./disable/zipsplit -v

            make -f unix/Makefile flags ZIP_LOCAL="-Werror" PROD=use-sys IZ_ZLIB=/tmp IZ_BZIP2=/tmp
            cat use-sys/flags
            make -f unix/Makefile generic PROD=use-sys

            ./use-sys/zip -v
            ./use-sys/zipnote -v
            ./use-sys/zipsplit -v
            