name: Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  configure:
    name: ${{ matrix.os }} + ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest


        compiler:
          - gcc-13
          - gcc-12
          - gcc-11
          - gcc-10
          - gcc-9
        #   - gcc-8
        #   - gcc-7

          - clang-15
          - clang-14
          - clang-13
          - clang-12
          - clang-11
        #   - clang-10
        #   - clang-9
        #   - clang-8
        #   - clang-7


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        ref: build

    - name: Install packages (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }}

    - name: Display ${{ matrix.compiler }} version
      run: ${{ matrix.compiler }} -v

    - name: configure (unix/Makefile)
      run: |
        make -f unix/Makefile flags CC=${{ matrix.compiler }}

    - name: change the flags file protos=${{ matrix.protos }} lzma=${{ matrix.lzma }}
      run: |
          sed -i.bak -e 's/CF="/CF=" -Werror /' flags
          cat flags

    - name: build (unix/Makefile)
      run: |
            make -f unix/Makefile generic CC=${{ matrix.compiler }}

    - name: Run zip --help
      run: ./zip --help

    - name: Run zip -v
      run: ./zip -v

    - name: Run zipcloak --help
      run: ./zipcloak --help

    - name: Run zipcloak -v
      run: ./zipcloak -v

    - name: Run zipnote --help
      run: ./zipnote --help

    - name: Run zipnote -v
      run: ./zipnote -v

    - name: Run zipsplit --help
      run: ./zipsplit --help

    - name: Run zipsplit -v
      run: ./zipsplit -v


    # - name: Upload build errors
    #   uses: actions/upload-artifact@v3
    #   if: failure()
    #   with:
    #     name: ${{ matrix.name }} (configure)
    #     path: |
    #       **/Makefile
    #       ${{ matrix.build-dir || '.' }}/configure.log
    #     retention-days: 30