name: NetBSD

# only run on demand
on: workflow_dispatch

jobs:
  configure:
    name: NetBSD 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - gcc

    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          run: |
            ${{ matrix.compiler }} -v
            make -f unix/Makefile flags CC=${{ matrix.compiler }}
            sed -i.bak -e 's/CF="/CF=" -Werror /' flags
            make -f unix/Makefile generic CC=${{ matrix.compiler }}
            ./zip -help
            ./zip -v
            ./zipnote -help
            ./zipnote -v
            ./zipsplit -help
            ./zipsplit -v