name: OpenBSD

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: OpenBSD
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - clang

    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          run: |
            ${{ matrix.compiler }} -v
            make -f unix/Makefile flags CC=${{ matrix.compiler }} ZIP_LOCAL="-Werror"
            cat flags
            make -f unix/Makefile generic
            ./zip -help
            ./zip -v
            ./zipnote -help
            ./zipnote -v
            ./zipsplit -help
            ./zipsplit -v