name: Solaris

# Long running - only run on demand

on:
    workflow_dispatch:
    # push:
    # pull_request:

jobs:
  solaris:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        prepare: |
            pkg install -–accept developerstudio-126
        run: |
            perl -V
            cc -V
