name: Solaris

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: Solaris
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
          # temp hard-code to build branch
          ref: build

      - name: Build
        uses: vmactions/solaris-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y ${{ matrix.compiler }}
          run: |
            ${{ matrix.compiler }} -v
            make -f unix/Makefile flags  ZIP_LOCAL="-Werror"
            cat flags
            make -f unix/Makefile generic
            ./zip -help
            ./zip -v
            ./zipnote -help
            ./zipnote -v
            ./zipsplit -help
            ./zipsplit -v
