name: Ubuntu

# Note - adding NO_ASM to the build for now. 32-bit build cores otherwise.
# See https://github.com/info-zip/zip-demo/issues/19

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: ${{ matrix.ubuntu }} + ${{ matrix.compiler }}
    runs-on: ${{ matrix.compiler }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - ubuntu: 22.04
          compiler: gcc-13
        - ubuntu: 22.04
          compiler: gcc-12
        - ubuntu: 22.04
          compiler: gcc-11
        - ubuntu: 22.04
          compiler: gcc-10
        - ubuntu: 20.04
          compiler: gcc-9
        - ubuntu: 20.04
          compiler: gcc-8
        - ubuntu: 20.04
          compiler: gcc-7

        - ubuntu: 22.04
          compiler: clang-17
        - ubuntu: 22.04
          compiler: clang-16
        - ubuntu: 22.04
          compiler: clang-15
        - ubuntu: 22.04
          compiler: clang-14
        - ubuntu: 22.04
          compiler: clang-13
        - ubuntu: 22.04
          compiler: clang-12
        - ubuntu: 22.04
          compiler: clang-11
        - ubuntu: 20.04
          compiler: clang-10
        - ubuntu: 20.04
          compiler: clang-9
        - ubuntu: 20.04
          compiler: clang-8

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        show-progress: 'false'

    - name: Install packages
      run: |
        apt-get update -qq
        apt-get install -yq ${{ matrix.compiler }}

    - name: Display ${{ matrix.compiler }} version
      run: ${{ matrix.compiler }} -v

    # - name: configure (unix/Makefile)
    #   run: |
    #     make -f unix/Makefile flags CC=${{ matrix.compiler }} LOCAL_ZIP="-Werror -DNO_ASM" ${{ matrix.opts }}
    #     cat flags

    # - name: build (unix/Makefile)
    #   run: |
    #         make -f unix/Makefile generic

    # - name: Run zip -v
    #   run: ./zip -v

    # - name: Run zipcloak -v
    #   run: ./zipcloak -v

    # - name: Run zipnote -v
    #   run: ./zipnote -v

    # - name: Run zipsplit -v
    #   run: ./zipsplit -v

