name: Debian

# Note - adding NO_ASM to the build for now. 32-bit build cores otherwise.
# See https://github.com/info-zip/zip-demo/issues/19

# Set to manual execution only for now.
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  configure:
    name: ${{ matrix.ubuntu }} + ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ubuntu: 22.04
          compiler: gcc
        - ubuntu: 22.04
          compiler: clang

        - ubuntu: 20.04
          compiler: gcc
        - ubuntu: 20.04
          compiler: clang


    container:
      image: ubuntu:${{ matrix.ubuntu }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        show-progress: 'false'

    - name: Install packages
      run: |
        apt-get update -qq
        apt-get install -yq ${{ matrix.compiler }}

    - name: Display ${{ matrix.compiler }} version
      run: ${{ matrix.compiler }} -v

    # - name: configure (unix/Makefile)
    #   run: |
    #     make -f unix/Makefile flags CC=${{ matrix.compiler }} LOCAL_ZIP="-Werror -DNO_ASM" ${{ matrix.opts }}
    #     cat flags

    # - name: build (unix/Makefile)
    #   run: |
    #         make -f unix/Makefile generic

    # - name: Run zip -v
    #   run: ./zip -v

    # - name: Run zipcloak -v
    #   run: ./zipcloak -v

    # - name: Run zipnote -v
    #   run: ./zipnote -v

    # - name: Run zipsplit -v
    #   run: ./zipsplit -v

