name: Windows Visual Studio (cl)



on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:


    msvc:
        name: Windows Visual Studio
        runs-on: windows-latest
        strategy:
          fail-fast: false
  
        steps:

        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v2
          with:
            vs-version: 17
          
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            show-progress: 'false'

        - name: Run msbuild
          run: |
            msbuild zip.sln 
          working-directory: win32\vc17

            # msbuild zip.sln -t:rebuild -property:OutDir=c:\develop\windows-bin\ -p:Configuration=Debug -p:EnableASAN=true

